"use client";

import { useEffect, useMemo, useState } from "react";
import { UserButton } from "@clerk/nextjs";
import { AlertTriangle, Camera, CheckCircle2, Clock3, Cpu, Radio, Thermometer, WifiOff } from "lucide-react";
import type { PrinterStatus, PrinterView } from "@/lib/types";
import { LiveView } from "./live-view";

const statusMeta: Record<PrinterStatus, { label:string; color:string; dot:string }> = {
  offline: { label: "오프라인", color: "text-muted", dot: "bg-muted" }, idle: { label: "대기", color: "text-muted", dot: "bg-muted" }, printing: { label: "출력 중", color: "text-primary", dot: "bg-primary" }, completed: { label: "완료", color: "text-success", dot: "bg-success" }, suspected: { label: "확인 필요", color: "text-warning", dot: "bg-warning" }, failed: { label: "실패 감지", color: "text-danger", dot: "bg-danger" },
};
function value(input:number|null, suffix:string) { return input === null ? "—" : `${Math.round(input)}${suffix}`; }

export function Dashboard({ initialPrinters, user, testMode }: { initialPrinters: PrinterView[]; user:{name:string;email:string}; testMode:boolean }) {
  const [printers, setPrinters] = useState(initialPrinters);
  const [selectedId, setSelectedId] = useState(initialPrinters[0]?.id);
  const selected = printers.find((printer) => printer.id === selectedId) ?? printers[0];
  useEffect(() => { const timer = window.setInterval(async () => { const response = await fetch("/api/app/dashboard", { cache: "no-store" }); if (response.ok) setPrinters((await response.json()).printers); }, 5000); return () => clearInterval(timer); }, []);
  const counts = useMemo(() => ({ active: printers.filter((p) => p.status === "printing").length, alerts: printers.filter((p) => p.status === "failed" || p.status === "suspected").length, online: printers.filter((p) => p.status !== "offline").length }), [printers]);
  if (!selected) return null;
  const meta = statusMeta[selected.status];
  return (
    <main className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface"><div className="mx-auto flex h-14 max-w-[1500px] items-center justify-between px-4 sm:h-16 sm:px-5 lg:px-8"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-control border border-border bg-chrome text-primary"><Camera size={18} /></div><div><p className="text-sm font-semibold tracking-tight">PrintWatch</p><p className="font-mono text-[10px] tracking-[0.12em] text-muted">DIMIGO FAB LAB</p></div></div><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-xs font-medium">{user.name}</p><p className="text-[11px] text-muted">{user.email}</p></div>{testMode ? <div className="grid h-8 w-8 place-items-center rounded-full bg-primary font-mono text-xs text-primary-foreground">LR</div> : <UserButton />}</div></div></header>
      <div className="mx-auto max-w-[1500px] px-4 py-5 sm:px-5 sm:py-6 lg:px-8 lg:py-8">
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 font-mono text-xs tracking-[0.14em] text-primary">FLEET OVERVIEW</p><h1 className="text-2xl font-semibold tracking-[-0.035em] sm:text-3xl">프린터 모니터링</h1><p className="mt-2 text-sm text-muted">상태를 확인하고 이상 징후가 있는 장비부터 살펴보세요.</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 border-l border-border pl-4 font-mono text-xs sm:pl-5"><span><b className="mr-2 text-lg text-foreground">{counts.online}</b><span className="text-muted">ONLINE</span></span><span><b className="mr-2 text-lg text-primary">{counts.active}</b><span className="text-muted">PRINTING</span></span><span><b className={`mr-2 text-lg ${counts.alerts ? "text-danger" : "text-foreground"}`}>{counts.alerts}</b><span className="text-muted">ALERTS</span></span></div></div>
        <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_340px]">
          <div className="order-2 overflow-hidden rounded-panel border border-border bg-surface lg:order-1"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div className="flex items-center gap-3"><span className={`h-2.5 w-2.5 rounded-full ${meta.dot}`} /><div><h2 className="text-sm font-semibold">{selected.name}</h2><p className={`text-xs ${meta.color}`}>{meta.label}</p></div></div><span className="font-mono text-[11px] text-muted">{selected.id.toUpperCase()}</span></div><LiveView key={selected.id} printerId={selected.id} snapshotUrl={selected.snapshotUrl} />
            <div className="grid grid-cols-2 border-t border-border sm:grid-cols-4">{[[Thermometer,"노즐",value(selected.telemetry.hotendCelsius,"°C")],[Thermometer,"베드",value(selected.telemetry.bedCelsius,"°C")],[Clock3,"경과",selected.telemetry.elapsedSeconds === null ? "—" : `${Math.floor(selected.telemetry.elapsedSeconds/60)}분`],[Cpu,"진행",value(selected.telemetry.progressPercent,"%")]].map(([Icon,label,data],index)=><div key={String(label)} className={`flex items-center gap-3 px-4 py-4 ${["", "border-l border-border", "border-t border-border sm:border-l sm:border-t-0", "border-l border-t border-border sm:border-t-0"][index]}`}><Icon size={16} className="text-muted"/><div><p className="text-[11px] text-muted">{String(label)}</p><p className="mt-0.5 font-mono text-sm">{String(data)}</p></div></div>)}</div>
          </div>
          <aside className="order-1 overflow-hidden rounded-panel border border-border bg-surface lg:order-2"><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">장비 상태</h2><p className="mt-1 text-xs text-muted">Ender-3 V3 SE · 3대</p></div><div>{printers.map((printer) => { const item=statusMeta[printer.status]; return <button key={printer.id} onClick={()=>setSelectedId(printer.id)} className={`flex w-full items-center gap-4 border-b border-border px-4 py-3.5 text-left transition-colors hover:bg-chrome sm:py-4 ${printer.id===selected.id ? "bg-chrome" : ""}`}><span className={`h-2.5 w-2.5 rounded-full ${item.dot}`} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><span className="text-sm font-medium">{printer.name}</span><span className={`text-xs ${item.color}`}>{item.label}</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-primary" style={{width:`${printer.telemetry.progressPercent ?? 0}%`}} /></div><div className="mt-2 flex justify-between font-mono text-[10px] text-muted"><span>{printer.telemetry.serialConnected ? "SERIAL OK" : "SERIAL —"}</span><span>{value(printer.telemetry.progressPercent,"%")}</span></div></div></button>; })}</div></aside>
        </section>
        <section className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="overflow-hidden rounded-panel border border-border bg-surface"><div className="flex items-center gap-2 border-b border-border px-4 py-3"><AlertTriangle size={16} className={selected.analysis?.verdict === "failed" ? "text-danger" : "text-muted"}/><h2 className="text-sm font-semibold">AI 판정 근거</h2></div><div className="grid gap-6 p-5 sm:grid-cols-[180px_1fr]"><div><p className="text-xs text-muted">실패 확률</p><p className="mt-2 font-mono text-4xl tracking-[-0.04em]">{selected.analysis ? `${Math.round(selected.analysis.failureProbability*100)}%` : "—"}</p></div><div><p className="text-xs text-muted">최근 관찰</p><p className="mt-2 text-sm leading-6">{selected.analysis?.summary ?? "분석할 이미지가 아직 없습니다. 에이전트가 연결되면 현재 장면과 이전 장면을 비교합니다."}</p><p className="mt-3 font-mono text-[10px] uppercase tracking-wider text-muted">QWYTHOS-V2-9B · {selected.analysis?.failureType ?? "WAITING"}</p></div></div></div><div className="rounded-panel border border-border bg-surface p-5"><div className="flex items-start gap-3">{counts.alerts ? <AlertTriangle className="text-warning" size={20}/> : <CheckCircle2 className="text-success" size={20}/>}<div><h2 className="text-sm font-semibold">{counts.alerts ? `${counts.alerts}대 확인 필요` : "확인할 경보 없음"}</h2><p className="mt-2 text-xs leading-5 text-muted">AI 판정은 작업자의 확인을 돕는 근거입니다. 출력 제어 명령은 전송하지 않습니다.</p></div></div><div className="mt-5 flex items-center gap-2 border-t border-border pt-4 font-mono text-[10px] text-muted">{counts.online ? <Radio size={13}/> : <WifiOff size={13}/>} {counts.online}/3 AGENTS CONNECTED</div></div></section>
      </div>
    </main>
  );
}
